# Generated by Django 4.1.3 on 2022-11-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
